### ISSUE TITLE
Authme unrestrictions not working.

### ISSUE THREAD

**Issue by LuxusDarkangel** [GotoFinal/AutoIn#21]
I have tested the new versiong (This is how i supposed it works: You have your authme config.yml, where you set the unrestricted names, so AutoIn read this cfg, takes the unrestricted names from authme config and let this usernames join without login)
It continues preventing BuildCraft, for example, from break blocks because it's not logged in (removing authme solves this).
Here you can see my authme cfg:
http://pastebin.com/XqyKBWpG

**Comment by LuxusDarkangel** [comment]
Any news about this?

**Comment by GotoFinal** [comment]
it will be fixed in new version, but I need find some time ;)

**Comment by GotoFinal** [comment]
I currently can't even use unrestricted-nicknames without AutoIn, can you send my any working AuthMe configuration with unrestricted names?

**Comment by GotoFinal** [comment]
ok, I added:
``` yaml
      ForceLogin:
        UseRegEx: false # Allow use RegEx in nicknames list, like 'Test\\d{1,3}'
        Nicknames: # Nicknames from this list don't need use login or register command, use to supprot mods like buildcraft and others
        - "nickname"
```
should work fine.
