### ISSUE TITLE
AutoIn bungeecord error

### ISSUE THREAD

**Issue by haelexuis** [GotoFinal/AutoIn#37]
I have problem with loading plugin in bungeecord, I have AuthMe (on Spigot) and AutoIn (bungee + spigot).

Spigot config: http://pastebin.com/mQ0w0HsK
Bungeecord config: http://pastebin.com/RBA80b5D
Error in console: http://pastebin.com/v1GdMduJ

Server have usually open 300 files, but in this error server have 4000 open files.

**Comment by GotoFinal** [comment]
Invalid configuration... 

Why you have handler and listener on both of servers? 
Bungee -> handler
Spigot -> listener, with this same servername as in bungee config.yml.

**Comment by haelexuis** [comment]
Ah, now it workd but if I join with orig. launcher server get this error - http://pasteboard.co/193CXBpA.png

**Comment by haelexuis** [comment]
In console (Warez + Orig): http://pastebin.com/sbHe5s6E

**Comment by GotoFinal** [comment]
so you still have something wrong, for this error it can be:
1. You don't have valid server name in spigot AutoIn config.
2. Wrong ports.
3. Bad configuration of system/firewall

**Comment by haelexuis** [comment]
You see, ports is OK and server name in spigot autoin config is "bungeecord" (i don't now why) because bungeecord server don't have name in config.. it's proxy.
In bungeecord config I have lobby server
servers: 
  lobby: 
    address: "93.91.250.141:27505"
    motd: Lobby
    restricted: false

**Comment by haelexuis** [comment]
I changed name in lobby autoin config on "lobby" and still not works

**Comment by GotoFinal** [comment]
paste current logs from both servers (from start to login), and configurations, + include bungeecord config...

**Comment by haelexuis** [comment]
Yes wait, btw if I set ip forward and in spigot config bungeecord true, if I connect with orig. plugin say: https://cdn.pbrd.co/images/196gkLIC.png

**Comment by haelexuis** [comment]
Spigot - http://pastebin.com/ThBBXNdV
BungeeCord - http://pastebin.com/g0MKQeTM

**Comment by GotoFinal** [comment]
and configs? and bungee cfg?
Also try change spigot online-mode to false (if it is true)

**Comment by haelexuis** [comment]
Online mode is false on both servers, configs:
Spigot cfg - http://pastebin.com/cps16mZr
BungeeCord cfg - http://pastebin.com/0aSXFjP7

**Comment by GotoFinal** [comment]
I don't want spigot config, I want AutoIn configs on spigot and bungee... + that that bungee config that you sent now.

**Comment by haelexuis** [comment]
I send you configs in first time.. okay I send again
bungee - https://gist.github.com/haelexuis/f4d8d8a11a99fce40a61
spigot - https://gist.github.com/haelexuis/335ff7cd88d9f24db219

**Comment by GotoFinal** [comment]
try change host in your bungee AutoIn to `93.91.250.160` and if that not work... you can also try `0.0.0.0` and if it still not work, there must be something that block AutoIn.

**Comment by haelexuis** [comment]
Host? Listener in bungee is offline and handler don't have host, btw I try connect only to spigot server http://pasteboard.co/1989V5mV.png with orig acc and it works.. but want login.

**Comment by haelexuis** [comment]
Omg, i use localhost, not spigot server -,-

**Comment by haelexuis** [comment]
It works! (I try setup this because spigot want login, i want set up: if I have org MC bungee connect me to another spigot server.

**Comment by haelexuis** [comment]
How I set up spigot server where plugin send orig players and server where plugin send offline players (where in bungee autoin cgf)?

**Comment by GotoFinal** [comment]
https://gist.github.com/haelexuis/f4d8d8a11a99fce40a61#file-gistfile1-txt-L265-L296
like:
``` yaml
    ForcedServers:
      PREMIUM:
        Enabled: true
 
        # works like "default_server" from bungee
        Server: "premiumServer"
 
        # works like "force_default_server" from bungee
        Force: true
		
        # like "fallback_server" from bungee
        Fallback: "lobby"
      CRACKED:
        Enabled: true
        Server: "crackedServer"
        Fallback: "lobby"
        Force: true
      EXCEPTION:
        Enabled: true
        # Players with Exception status will use this same settings as Cracked players.
        Parent: CRACKED
      ERROR:
        Enabled: true
        Parent: CRACKED
```
Set this only in bungee AutoIn cfg, spigot AutoIn ignores this section.
